# Generated by Django 3.2 on 2021-04-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
